/**
 * common dll - Some dll files are generated by webpack.dll.config.js, including vue, vue-router, lodash, core-js
 */
const path = require('path');
const webpack = require('webpack');
const AddAssetHtmlPlugin = require('add-asset-html-webpack-plugin');

module.exports = (config, { root }) => {
    const __DEV__ = process.env.NODE_ENV === 'development';
    config
        .plugin('dll-refer')
        .use(webpack.DllReferencePlugin, [{
            context: root,
            manifest: __DEV__ ? require('../dll/vendorDll.dev.manifest.json') : require('../dll/vendorDll.manifest.json'),
            // manifest: require('../dll/vendorDll.manifest.json'),
        }])
        .end()
        .plugin('dll-insert')
        .use(AddAssetHtmlPlugin, [{
            // Temporarily hide the warning, and then release it when the business type errors are almost handled.
            filepath: __DEV__ ? path.resolve(__dirname, '../dll/vendorDll-dev.js') : path.resolve(__dirname, '../dll/vendorDll.*.js'),
            // filepath: path.resolve(__dirname, '../dll/vendorDll.*.js'),
        }])
        .end();
    return config;
};
